### PR TITLE
Add CaNS simulator

### PR DESCRIPTION
**Pull request by Pbarbosa92**
This PR adds the CaNS simulator to kutu.

### CODE REVIEW

**Comment by sarmento** [comment]
Glad to see this happening! :)

**Comment by Pbarbosa92** [comment]
Ran a small test on the CaNS GPU.
mpirun --allow-run-as-root --np 1 --use-hwthread-cpus /CaNS/run/cans
Captura de ecrã 2024-04-30, às 14 31 52
(We can confirm that we are using the GPU)

**Comment by Pbarbosa92** [comment]
Trying to run with --np 2 or higher produces a lot of errors.
Some errors are related to hcoll.
"HCOLL is designed to optimize communication patterns in parallel computing environments, particularly in the context of MPI (Message Passing Interface) applications."
Since we are not yet running this on a cluster, let's disable hcoll by doing `export OMPI_MCA_coll=^hcoll`.

We are now left with the NCCL errors. After increasing the verbosity by doing `export NCCL_DEBUG=WARN` we are left with:
```
root@3b7925d1170d:/home/cans-input-example# mpirun --allow-run-as-root --np 2 --use-hwthread-cpus /CaNS/run/cans clear
NCCL version 2.18.5+cuda12.2

3b7925d1170d:4568:4568 [0] init.cc:795 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 1000

3b7925d1170d:4569:4569 [0] init.cc:795 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 1000
CUDECOMP:ERROR: /CaNS/dependencies/cuDecomp/src/cudecomp.cc:69 NCCL error. (error code 5)
CUDECOMP:ERROR: /CaNS/dependencies/cuDecomp/src/cudecomp.cc:69 NCCL error. (error code 5)

3b7925d1170d:4569:4569 [0] init.cc:795 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 1000

3b7925d1170d:4568:4568 [0] init.cc:795 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 1000
CUDECOMP:ERROR: /CaNS/dependencies/cuDecomp/src/cudecomp.cc:69 NCCL error. (error code 5)
CUDECOMP:ERROR: /CaNS/dependencies/cuDecomp/src/cudecomp.cc:69 NCCL error. (error code 5)
```
We have more errors, like `CUDECOMP:ERROR: /CaNS/dependencies/cuDecomp/src/cudecomp.cc:126 Invalid usage. (invalid grid descriptor)` but they can just be created by the NCCL errors. I'll focus on the nccl errors for now.

**Comment by sarmento** [comment]
I suggest that, if you are running into too many problema, you should talk directly with the developer :) He is happy to help us.

**Comment by Pbarbosa92** [comment]
After reading https://github.com/NVIDIA/nccl/issues/32 it seems that CaNS is giving unique ranks to multiple process and that results in the "Duplicate GPU detected" warning.

**Comment by Pbarbosa92** [comment]
CaNS GPU https://github.com/inductiva/kutu/tree/pb-add-CaNS-gpu

**Review by sergiomsantos — APPROVED** [review]

**Pull request merged**
