### PR TITLE
Improve openfoam env

### PR DESCRIPTION
**Pull request by Pbarbosa92**
Issue https://github.com/inductiva/tasks/issues/523

### CODE REVIEW

**Comment by hpenedones** [comment]
Thanks @Pbarbosa92 : are the changes fully back-compatible or do we need to update something also on the Python client, and/or on the example scripts in the tutorials, etc?

**Comment by Pbarbosa92** [comment]
> Thanks @Pbarbosa92 : are the changes fully back-compatible or do we need to update something also on the Python client, and/or on the example scripts in the tutorials, etc?

It should be. I only removed the source file and created the env vars by hand.

**Comment by hpenedones** [comment]
> > Thanks @Pbarbosa92 : are the changes fully back-compatible or do we need to update something also on the Python client, and/or on the example scripts in the tutorials, etc?
> 
> It should be. I only removed the source file and created the env vars by hand.

Ok, cool. Do you need to run some end to end simulations, from the Python client, to double check?

**Comment by Pbarbosa92** [comment]
I just ran our example simulation for both and they both worked fine. With this changes I believe we can remove the usage of the launch.sh from the task-runner. And after removing it there we can completely remove the files.

**Comment by sarmento** [comment]
Ok! Lmk when this is at a point we can demo  it to some of our partners.

**Comment by Pbarbosa92** [comment]
> Ok! Lmk when this is at a point we can demo it to some of our partners.

We can already do a demo using a custom docker container (executing the allrun script).
I'll have a meeting tomorrow to talk about allowing the execution of any commands on the vm's.

**Pull request merged**
