### PR TITLE
Add xbeach 1.24r6082

### PR DESCRIPTION
**Pull request by sergiomsantos**

### CODE REVIEW

**Comment by sarmento** [comment]
Thank you for this!

**Comment by Pbarbosa92** [comment]
Xbeach 1.24 - 662.71 MB ===> 94.57 MB

**Comment by sarmento** [comment]
AMAZING!

**Comment by sergiomsantos** [comment]
> Xbeach 1.24 - 662.71 MB ===> 94.57 MB

lindo!!!

**Pull request merged**
